### ISSUE TITLE
Однострочный аналог removeExcessWhitespaces.

### ISSUE THREAD

**Issue by runewalsh** [PoppyFanboy/Snake-Game#7]
`" ‌ ‌ Будьте ‌ ‌ терпеливы,\n ‌ ‌ ‌ ‌ я ‌ ‌ ‌ аутист. ‌ ‌ ".replaceAll("\\s+", " ").trim()`
⇓
`Будьте терпеливы, я аутист.`

Кстати, для эскейпов тоже можно заюзать `replaceAll`.

**Comment by PoppyFanboy** [comment]
Когда-нибудь я перестану писать велосипеды. Вроде поправил

**Comment by runewalsh** [comment]
>`\\s+|\\t|\\n`

Это не нужно, класс `\s` («whitespace») включает все эти символы.

Ну и тогда уж `(\\s|др. символ1|др. символ2)+`, если только ты действительно не хочешь заменить на пробелы «один и более пробелов, или ОДИН символ1, или ОДИН символ2».

**Comment by runewalsh** [comment]
>`\\s+|\\t|\\n`

Это не нужно, класс `\s` («whitespace») включает все эти символы.

Ну и тогда уж `(\\s|др. символ1|др. символ2)+`, если только ты действительно не хочешь заменить на пробелы «один и более пробельных символов, или ОДИН символ1, или ОДИН символ2».
